In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
%matplotlib inline

In [3]:
cotinine_levels = np.random.randint(low=0, high=500, size=40)
cotinine_levels.shape

(40,)

In [4]:
np.sort(cotinine_levels)

array([  5,   8,  25,  25,  36,  40,  64,  65,  85, 124, 127, 136, 139,
       139, 140, 144, 171, 185, 212, 222, 227, 274, 277, 299, 303, 316,
       344, 373, 375, 395, 402, 414, 421, 441, 446, 449, 454, 458, 474,
       481])

In [5]:
plt.hist(cotinine_levels, bins=7)

(array([8., 7., 3., 4., 5., 4., 9.]),
 array([  5.,  73., 141., 209., 277., 345., 413., 481.]),
 <a list of 7 Patch objects>)

In [6]:
bins = [
    (0, 99),
    (100, 199),
    (200, 299),
    (300, 399),
    (400, 499)
]

In [7]:
counts = [0] * 5
counts

[0, 0, 0, 0, 0]

In [8]:
for cl in cotinine_levels:
    if 0 <= cl <= 99:
        counts[0] += 1
    elif 100 <= cl <= 199:
        counts[1] += 1
    elif 200 <= cl <= 299:
        counts[2] += 1
    elif 300 <= cl <= 399:
        counts[3] += 1
    elif 400 <= cl <= 499:
        counts[4] += 1

In [9]:
counts

[9, 9, 6, 6, 10]

In [10]:
for (lower, upper), count in zip(bins, counts):
    print(f"{lower}-{upper}\t{count}")

0-99	9
100-199	9
200-299	6
300-399	6
400-499	10


In [2]:
arr1 = [("Positive", "Negative"), (1, -1), (2, -2), (3, -3), (4, -4)]
arr2 = ["x10", 10, 20, 30, 40]
for (posx, negx), y in zip(arr1, arr2):
    print(posx, negx, y)

Positive Negative x10
1 -1 10
2 -2 20
3 -3 30
4 -4 40


# Assignment 5/11
## Main Assignment

  * Define the terms **Class Boundaries**, **Class Limits**, and **Class Width**.
  * What is the difference between the term *class* and the term *bin* the way we have used above?
  * Create a dataset with 1000 elements, with each element being between 50 and 5000. Then print a frequency distribution table. Decide upon the class boundaries, limits, and width yourself. Mention what you chose for each and why.

## Stretch Assignment
In the for-loop, instead of hard-coding the class limits in the if-condition, use the `bins` array to check which bin an element belongs to.

In [13]:
print("hello world")

hello world
